import Head from "next/head";

import { Navbar, Banner, Aboutus, Digital, Dedicated, Manage, FAQ, Footer, Wework } from "@landing";

const Home = () => {
  return (
    <>
      <Head>
        <title>Coinvester</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Banner />
        <Aboutus />
        <Dedicated />
        <Digital />
        <Wework />
        <Manage />
        <FAQ />
        <Footer />
      </main>
    </>
  );
};

export default Home;
